# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField()),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_order', models.TextField()),
                ('next_assessment', models.IntegerField(blank=True, null=True)),
                ('completed_assessments', models.TextField(blank=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_is_confirmed', models.BooleanField(default=False)),
                ('institution', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=510)),
                ('abstract', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('year', models.CharField(blank=True, max_length=30)),
                ('journal', models.CharField(blank=True, max_length=254)),
                ('volume', models.CharField(blank=True, max_length=30)),
                ('issue', models.CharField(blank=True, max_length=30)),
                ('pages', models.CharField(blank=True, max_length=30)),
                ('doi', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now)),
                ('results', models.TextField()),
            ],
            options={
                'get_latest_by': 'date_searched',
            },
        ),
        migrations.CreateModel(
            name='SearchString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string_for_title_and_abstract', models.TextField()),
                ('search_string_for_references', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['topic'],
            },
        ),
        migrations.AddField(
            model_name='searchstring',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic'),
        ),
        migrations.AddField(
            model_name='search',
            name='search_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.SearchString'),
        ),
        migrations.AddField(
            model_name='search',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Source'),
        ),
        migrations.AddField(
            model_name='search',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic'),
        ),
        migrations.AddField(
            model_name='publication',
            name='search_topics',
            field=models.ManyToManyField(to='engine.Topic'),
        ),
        migrations.AddField(
            model_name='publication',
            name='searches',
            field=models.ManyToManyField(blank=True, to='engine.Search'),
        ),
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(blank=True, to='engine.Topic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentstatus',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Publication'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic'),
        ),
    ]
