# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('test_recall', models.FloatField()),
                ('target_recall', models.FloatField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.FloatField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Publication')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic')),
            ],
        ),
    ]
