# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_mlmodel_mlprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=254)),
                ('note', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('n_users', models.IntegerField()),
                ('n_publications', models.IntegerField()),
                ('n_assessments', models.IntegerField()),
                ('n_assessed_publications', models.IntegerField()),
                ('max_publication_pk', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'date_time',
            },
        ),
    ]
