# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20180711_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_assessments', models.IntegerField()),
                ('n_relevant', models.IntegerField()),
                ('relevance', models.FloatField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Publication')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Topic')),
            ],
        ),
    ]
