# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_humanprediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanprediction',
            options={'ordering': ['-relevance', '-n_assessments']},
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_attainment',
            field=models.IntegerField(choices=[(0, 'No formal education'), (1, 'Secondary school'), (2, 'Degree'), (3, 'Masters'), (4, 'Doctorate'), (5, 'Postdoctoral Research'), (6, 'Lecturer'), (7, 'Reader'), (8, 'Professor')], default=0),
        ),
    ]
